name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
        echo "Current directory: $(pwd)"
        echo "Listing home directory:"
        ls -la ~

        echo "Installing Node.js..."
        if ! command -v nvm &> /dev/null; then
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
        fi
        nvm install node

        echo "Installing PM2..."
        if ! command -v pm2 &> /dev/null; then
          npm install -g pm2
        fi

        REPO_URL="git@github.com:PantelisTsagkas/github-aws-ec2.git"
        BRANCH="main"
        REPO_DIR="$HOME/github-aws-ec2"

        # Ensure SSH is set up for GitHub
        mkdir -p ~/.ssh
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts 2>/dev/null

        echo "Cloning or updating repository..."
        if [ -d "$REPO_DIR/.git" ]; then
          cd "$REPO_DIR"
          git pull origin "$BRANCH" || echo "Failed to pull updates"
        else
          git clone "$REPO_URL" "$REPO_DIR" || { echo "Failed to clone repository"; exit 1; }
          cd "$REPO_DIR" || { echo "Failed to change directory"; exit 1; }
        fi

        # Make sure we can access the simple-web-server directory
        if [ -d "$REPO_DIR/simple-web-server" ]; then
          cd "$REPO_DIR/simple-web-server" || { echo "Failed to change to simple-web-server directory"; exit 1; }
          echo "Installing npm dependencies..."
          npm install

          echo "Starting/restarting application..."
          pm2 restart server.js || pm2 start server.js
        else
          echo "Error: simple-web-server directory not found"
          echo "Contents of $REPO_DIR:"
          ls -la "$REPO_DIR"
          exit 1
        fi
        '
